workdir: "/home/jarlehti/projects/gradu"

datasets:
  "binary4d": "data/datasets/binary4d.csv"
  "binary3d": "data/datasets/binary3d.csv"
  #"adult": "data/datasets/cleaned_adult_data_v2.csv"
epsilons:
  - "01"
  - "03"
  - "10"
  - "30"
  - "80"
MCMC_algorithms:
  - "NUTS"
n_synt_datasets: 10
queries:
  "binary4d":
    - []
    - [['A', 'B']]
    - [['A', 'C']]
    - [['A', 'D']]
    - [['B', 'C']]
    - [['C', 'D']]
    - [['A', 'B'], ['A', 'C']]
    - [['B', 'C'], ['C', 'D']]
    - [['A', 'B'], ['B', 'C'], ['C', 'D']]

  "binary3d":
    - []
    - [['A', 'B']]
    - [['A', 'C']]
    - [['B', 'C']]
    - [['A', 'B'], ['B', 'C'], ['A', 'C']]
