datasets:
  "binary4d": "binary4d.csv"
  #"adult": "cleaned_adult_data_v2.csv"
epsilons:
  - "01"
  - "03"
  - "05"
  - "07"
  - "10"
  - "30"
  - "50"
  - "80"
MCMC_algorithms:
  - "NUTS"
  - "HMC"
# MCMC_algorithms = ["NUTS", "HMC", "DataAugMCMC"]
n_datasets: 10