workdir: "/home/jarlehti/projects/gradu"

datasets:
  "binary4d": "binary4d.csv"
  "binary3d": "binary3d.csv"
  #"adult": "cleaned_adult_data_v2.csv"
epsilons:
  - "01"
  - "03"
  - "10"
  - "30"
  - "80"
MCMC_algorithms:
  - "NUTS"
n_synt_datasets: 10
queries:
  "binary4d":
    - []
    - ['A', 'B']
    - ['A', 'C']
    - ['A', 'D']
    - ['B', 'C']
    - ['C', 'D']
    - ['A', 'B', 'C']
    - ['B', 'C', 'D']
  "binary3d":
    - []
    - ['A', 'B']
    - ['A', 'C']
    - ['B', 'C']
    - ['A', 'B', 'C']