cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
directory: "/wrk-vakka/users/jarlehti/gradu"
restart-times: "3"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "1"
local-cores: "4"
latency-wait: "5"
use-conda: "True"
use-singularity: "False"
jobs: "10"
printshellcmds: "True"
jobname: "jakki-gradu.{name}.{jobid}"
rerun-incomplete: "True"
cores: "4"

# Example resource configuration
default-resources:
  - runtime=120
  - mem_mb=6000
  - disk_mb=10000
# # set-threads: map rule names to threads
#set-threads:
#  - single_core_rule=1
#  - multi_core_rule=4
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
